services:
  mongo:
    image: mongo
    container_name: tabs_mongo
    ports:
      - "27017:27017"

  server:
    image: node:22
    container_name: tabs_server
    working_dir: /app
    volumes:
      - ./tabs_server:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "8800:8800"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/tabs
    depends_on:
      - mongo

  client:
    image: node:20
    container_name: tabs_client
    working_dir: /app
    volumes:
      - ./tabs_client:/app
      - /app/node_modules
    command: sh -c "corepack enable && yarn install && yarn dev"
    ports:
      - "5173:5173"
    depends_on:
      - server
